
function imparPar(numero) {
    if (numero % 2 === 0) return "par"
    else { return "impar" }
}
const resultadoIP = imparPar(18)
console.log(resultadoIP)
function comprimentar(nome = "Usuario"){return`ola ${nome}!}Bem vindo (a)`}
const resultadoComprimentar = comprimentar ("outro nome")
// console.log (resultadoComprimentar)
Function clAreaRetangulo  (largura, altura){return largura*altura}
Exercico: function imparPar(numero"2**3*
){
    if (numero % 2 === 0) return 2*2*"par"
    else { return "impar" }


























